<a href="https://colab.research.google.com/github/AlfCR/dnn-estadia/blob/main/dnn_estadia_ACP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# LSTM y GRU en el mantenimiento predictivo de entornos vehiculares

## 1. Configuración Inicial y Verificación de Entorno

### Clonación del Repositorio y Configuración del Directorio

In [ ]:
#Celda 1
import os
if not os.path.exists('/content/dnn-estadia'):
    !git clone https://github.com/AlfCR/dnn-estadia.git
%cd /content/dnn-estadia

Cloning into 'dnn-estadia'...
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 15 (delta 3), reused 3 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (15/15), 39.92 KiB | 929.00 KiB/s, done.
Resolving deltas: 100% (3/3), done.
/content/dnn-estadia

### Verificación de Versiones de Frameworks de Aprendizaje Automático

In [ ]:
#Celda 2
#Verificación de disponibilidad y versión  de TensorFlow
import tensorflow as tf
print(tf.__version__)
print(tf.config.list_physical_devices('GPU'))

2.20.0
[]

In [ ]:
#Celda 3
#Verificación de  disponibilidad y versión  PyTorch
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.11.0+cpu
False


Observación: Eliminar
1) Indentificación de espacióis en el encabezado de la columna
2) Objetivo: si uno estos 10 archivos en un solo dataframe, ¿qué columnas me conviene conservar?
3) Intersección (20) = las columnas que SÍ están presentes en absolutamente todos los archivos
4) Unión (212) = todas las columnas que existen en al menos un archivo

**Nota: ** La norma para identificar las variables a usar bajo la norma SAE J1979 con las que se debe de implementar para el mantenimiento preventivo son las: {Identificar que variables van para esa normativa}-> implementar el mantenimiento predictivo.

Configuración para rutas

In [ ]:
# Celda 4
import os
import re
import numpy as np
import pandas as pd
import hashlib
import shutil

from google.colab import drive
drive.mount('/content/drive')

# Configuración de rutas
base = '/content/drive/MyDrive/Colab Notebooks/dataset'
carpeta1 = os.path.join(base, 'Measurement complementary')
carpeta2 = os.path.join(base, 'Mediciones Agosto 2024 Chiapas')
ruta_salida = os.path.join(base, 'dataset_limpio')

# Ruta de respado de las carpetas orignales
respaldo_dataset = os.path.join(base, 'respaldo_carpetas')

# Carpeta de salida
os.makedirs(ruta_salida, exist_ok=True)

# Validación de existencia de las carpetas
for i in (carpeta1, carpeta2):
    assert os.path.isdir(i), f"La carpeta {i} no existe"
    print(f"{os.path.basename(i)}: {len(os.listdir(i))} archivos")

for origen in (carpeta1, carpeta2):
    destino = os.path.join(respaldo_dataset, os.path.basename(origen))
    if os.path.exists(destino):
       print(f"Respado existente: {destino}")
    else:
        shutil.copytree(origen, destino)
        print(f"Respado creado: {destino}")

    # Verificación: mismos archivos y mismos tamaños
    tam_origen = {f: os.path.getsize(os.path.join(origen, f)) for f in os.listdir(origen)}
    tam_destino = {f: os.path.getsize(os.path.join(destino, f)) for f in os.listdir(destino)}

    assert tam_origen == tam_destino, f"El respado de {origen} no coincide con el original"
    print(f" Verificado: {len(tam_origen)} archivos con el mismo tamaño")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Measurement complementary: 11 archivos
Mediciones Agosto 2024 Chiapas: 6 archivos
Respado existente: /content/drive/MyDrive/Colab Notebooks/dataset/respaldo_carpetas/Measurement complementary
 Verificado: 11 archivos con el mismo tamaño
Respado existente: /content/drive/MyDrive/Colab Notebooks/dataset/respaldo_carpetas/Mediciones Agosto 2024 Chiapas
 Verificado: 6 archivos con el mismo tamaño

In [ ]:
# Celda 5: huellas SHA-256 de originales y respaldo
def calcular_sha256(ruta):
    h = hashlib.sha256()
    with open(ruta, 'rb') as f:
        # 1024 * 1024 para leer en bloques de 1 MB
        for bloque in iter(lambda: f.read(1024 * 1024), b''):
            h.update(bloque)
    return h.hexdigest()

filas = []
for carpeta in (carpeta1, carpeta2):
    nombre_carpeta = os.path.basename(carpeta)
    for nombre in sorted(os.listdir(carpeta)):
        ruta_original = os.path.join(carpeta, nombre)
        ruta_respaldo = os.path.join(respaldo_dataset, nombre_carpeta, nombre)
        filas.append({
            'carpeta': nombre_carpeta,
            'archivo': nombre,
            'tamano_kb': round(os.path.getsize(ruta_original) / 1024, 1),
            'sha256_original': calcular_sha256(ruta_original),
            'sha256_respaldo': calcular_sha256(ruta_respaldo),
        })

huellas = pd.DataFrame(filas)

# El respaldo debe ser idéntico al original
assert (huellas['sha256_original'] == huellas['sha256_respaldo']).all(), \
    "Hay archivos distintos entre el original y el respaldo"
print(f"Respaldo idéntico al original: {len(huellas)} archivos")

# Línea base: se guarda solo la primera vez; después, se compara contra ella
destino_huellas = os.path.join(ruta_salida, 'huellas_originales.csv')
if os.path.exists(destino_huellas):
    base_previa = pd.read_csv(destino_huellas)
    comp = huellas.merge(
        base_previa[['carpeta', 'archivo', 'sha256_original']],
        on=['carpeta', 'archivo'], how='outer', suffixes=('_hoy', '_base'))
    cambios = comp[comp['sha256_original_hoy'] != comp['sha256_original_base']]
    if cambios.empty:
        print("Los originales siguen idénticos a la línea base.")
    else:
        print(f"ATENCIÓN: archivos distintos o faltantes:\n{cambios}")
else:
    huellas.to_csv(destino_huellas, index=False)
    print(f"Línea base guardada en: {destino_huellas}")

# Vista corta (huella recortada a 12 caracteres)
huellas[['carpeta', 'archivo', 'tamano_kb']].assign(sha256=huellas['sha256_original'].str[:12])

Respaldo idéntico al original: 17 archivos
Los originales siguen idénticos a la línea base.

,carpeta,archivo,tamano_kb,sha256
0,Measurement complementary,trackLog-2022-nov-12_20-05-07.csv,3688.4,0a710f3e0d41
1,Measurement complementary,trackLog-2022-nov-13_00-03-52.csv,2893.0,2c3cdb0be236
2,Measurement complementary,trackLog-2022-nov-14_09-03-16.csv,2059.9,79633a18a410
3,Measurement complementary,trackLog-2022-nov-14_13-01-38.csv,1997.6,c51719174c03
4,Measurement complementary,trackLog-2022-nov-16_09-32-26.csv,2985.9,b49a45fc627b
5,Measurement complementary,trackLog-2022-nov-16_09-44-58.csv,2077.3,c7abe127ff57
6,Measurement complementary,trackLog-2022-nov-16_09-44-58.xlsx,1061.5,7532cf91c3d1
7,Measurement complementary,trackLog-2022-nov.-10_09-23-59 (1).csv,2539.3,9759ceee4913
8,Measurement complementary,trackLog-2022-nov.-11_12-47-43.csv,1760.4,5cce8384939b
9,Measurement complementary,trackLog-2022-nov.-11_14-46-26.csv,3585.9,ac8839f24405
10,Measurement complementary,trackLog-2022-nov.-27_12-43-04.csv,338.4,d3e3db59eed1
11,Mediciones Agosto 2024 Chiapas,torqueTrackLog(1).csv,604.1,85a55c14d9d4
12,Mediciones Agosto 2024 Chiapas,torqueTrackLog(2).csv,438.1,804a62f4ce0b
13,Mediciones Agosto 2024 Chiapas,torqueTrackLog(3).csv,296.4,038a441604cc
14,Mediciones Agosto 2024 Chiapas,torqueTrackLog(4).csv,691.5,57695bfa9b6e
15,Mediciones Agosto 2024 Chiapas,torqueTrackLog(5).csv,432.6,ed8f11de44b8
16,Mediciones Agosto 2024 Chiapas,torqueTrackLog.csv,130.8,d9d25be859f1

In [ ]:
# Celda 7: Auditar contenido y formato (por bloques de encabezado)
import csv
import io
from pathlib import Path

FALTANTES = {'', '-', '∞' ,'nan', 'NaN'}

def normalizar_texto(valor):
    if pd.isna(valor):
        return ''
    return str(valor).replace('\u00a0', ' ').strip()

def leer_filas(ruta):
    """Devuelve las filas como listas de texto, sin que pandas decida el ancho."""
    if ruta.suffix.lower() == '.xlsx':
        bruto = pd.read_excel(ruta, header=None, dtype='string', keep_default_na=False)
        return bruto.fillna('').values.tolist(), 'xlsx: primera hoja'
    for cod in ('utf-8-sig', 'cp1252'):
        try:
            with open(ruta, 'r', encoding=cod, newline='') as f:
                texto = f.read()
            break
        except UnicodeDecodeError:
            continue
    else:
        raise ValueError('No se pudo determinar la codificación del CSV.')
    try:
        sep = csv.Sniffer().sniff(texto[:8192], delimiters=',;\t|').delimiter
    except csv.Error:
        sep = ','
    filas = list(csv.reader(io.StringIO(texto, newline=''), delimiter=sep))
    return filas, f'csv: separador={sep!r}, encoding={cod}'

def partir_en_bloques(filas):
    """Un bloque = un encabezado (el primero o uno repetido) y las filas que le siguen."""
    pares = [(n, f) for n, f in enumerate(filas, start=1)
             if any(normalizar_texto(x) for x in f)]          # sin líneas en blanco
    if not pares:
        return []
    primer_campo = normalizar_texto(pares[0][1][0])
    bloques = []
    for n, fila in pares:
        if normalizar_texto(fila[0]) == primer_campo:
            bloques.append({'linea': n,
                            'encabezado': [normalizar_texto(x) for x in fila],
                            'filas': []})
        else:
            bloques[-1]['filas'].append(fila)
    return bloques

def auditar_bloques(bloques):
    vacia_por_columna = {}
    for b in bloques:
        for i, nombre in enumerate(b['encabezado']):
            etiqueta = nombre or f'__SIN_NOMBRE_{i + 1}'
            vacia = all((normalizar_texto(r[i]) in FALTANTES) if i < len(r) else True
                        for r in b['filas'])
            vacia_por_columna.setdefault(etiqueta, []).append(vacia)
    columnas = {n for n in vacia_por_columna if not n.startswith('__SIN_NOMBRE_')}
    vacias = sorted(n for n, v in vacia_por_columna.items() if all(v))
    duplicadas = sorted({n for b in bloques for n in b['encabezado']
                         if n and b['encabezado'].count(n) > 1})
    return columnas, vacias, duplicadas

esquemas, filas_reporte = {}, []
for carpeta in (carpeta1, carpeta2):
    for ruta in sorted(Path(carpeta).iterdir()):
        if (not ruta.is_file() or ruta.name.startswith('~$')
                or ruta.suffix.lower() not in ('.csv', '.xlsx')):
            continue
        clave = f'{ruta.parent.name}/{ruta.name}'
        try:
            filas, detalle = leer_filas(ruta)
            bloques = partir_en_bloques(filas)
            columnas, vacias, duplicadas = auditar_bloques(bloques)
            esquemas[clave] = columnas
            filas_reporte.append({
                'archivo': clave,
                'filas_datos': sum(len(b['filas']) for b in bloques),
                'n_bloques': len(bloques),
                'lineas_encabezado_repetido': [b['linea'] for b in bloques[1:]],
                'n_esquemas_distintos': len({tuple(b['encabezado']) for b in bloques}),
                'n_columnas': len(columnas),
                'columnas_duplicadas': duplicadas,
                'columnas_vacias': vacias,
                'lectura': detalle,
                'error': '',
            })
        except Exception as error:
            filas_reporte.append({'archivo': clave, 'error': str(error)})

# Columnas que le faltan a cada archivo respecto a la unión de SU carpeta (solo el conteo)
union_carpeta = {}
for clave, cols in esquemas.items():
    union_carpeta.setdefault(clave.split('/')[0], set()).update(cols)
for fila in filas_reporte:
    if fila['archivo'] in esquemas:
        nombre_carpeta = fila['archivo'].split('/')[0]
        fila['n_faltantes_vs_carpeta'] = len(union_carpeta[nombre_carpeta] - esquemas[fila['archivo']])

auditoria = pd.DataFrame(filas_reporte)
display(auditoria.drop(columns=['lectura']))

ruta_auditoria = os.path.join(ruta_salida, 'auditoria_archivos.csv')
auditoria.to_csv(ruta_auditoria, index=False)
print(f'Auditoría guardada en: {ruta_auditoria}')

,archivo,filas_datos,n_bloques,lineas_encabezado_repetido,n_esquemas_distintos,n_columnas,columnas_duplicadas,columnas_vacias,error,n_faltantes_vs_carpeta
0,Measurement complementary/trackLog-2022-nov-12...,2955,1,[],1,206,[],"[0-100kph Time(s), 0-100mph Time(s), 0-200kph ...",,3
1,Measurement complementary/trackLog-2022-nov-13...,2260,1,[],1,206,[],"[0-100kph Time(s), 0-100mph Time(s), 0-200kph ...",,3
2,Measurement complementary/trackLog-2022-nov-14...,1625,1,[],1,206,[],"[0-100kph Time(s), 0-100mph Time(s), 0-200kph ...",,3
3,Measurement complementary/trackLog-2022-nov-14...,1928,1,[],1,99,[],[Alcohol Fuel Percentage(%)],,110
4,Measurement complementary/trackLog-2022-nov-16...,2957,1,[],1,99,[],"[Alcohol Fuel Percentage(%), Boost Pressure Se...",,110
5,Measurement complementary/trackLog-2022-nov-16...,2013,1,[],1,99,[],"[Alcohol Fuel Percentage(%), Boost Pressure Se...",,110
6,Measurement complementary/trackLog-2022-nov-16...,2013,1,[],1,99,[],"[Alcohol Fuel Percentage(%), Boost Pressure Se...",,110
7,Measurement complementary/trackLog-2022-nov.-1...,2787,1,[],1,90,[],"[Engine kW (At the wheels)(kW), Fuel trim Bank...",,119
8,Measurement complementary/trackLog-2022-nov.-1...,3063,1,[],1,52,[],[],,157
9,Measurement complementary/trackLog-2022-nov.-1...,2858,1,[],1,206,[],"[0-100kph Time(s), 0-100mph Time(s), 0-200kph ...",,3
10,Measurement complementary/trackLog-2022-nov.-2...,876,1,[],1,32,[],[],,177
11,Mediciones Agosto 2024 Chiapas/torqueTrackLog(...,3905,3,"[852, 2800]",1,12,[],[__SIN_NOMBRE_13],,5
12,Mediciones Agosto 2024 Chiapas/torqueTrackLog(...,2632,4,"[6, 1959, 2623]",2,17,[],[__SIN_NOMBRE_13],,0
13,Mediciones Agosto 2024 Chiapas/torqueTrackLog(...,1956,2,[6],1,12,[],[__SIN_NOMBRE_13],,5
14,Mediciones Agosto 2024 Chiapas/torqueTrackLog(...,4470,4,"[852, 2800, 3909]",1,12,[],[__SIN_NOMBRE_13],,5
15,Mediciones Agosto 2024 Chiapas/torqueTrackLog(...,2797,2,[852],1,12,[],[__SIN_NOMBRE_13],,5
16,Mediciones Agosto 2024 Chiapas/torqueTrackLog.csv,850,1,[],1,12,[],[__SIN_NOMBRE_13],,5

Auditoría guardada en: /content/drive/MyDrive/Colab Notebooks/dataset/dataset_limpio/auditoria_archivos.csv

In [ ]:
# Celda 8: detalle por bloque
import hashlib

def huella_bloque(b):
    h = hashlib.sha256()
    for r in b['filas']:
        h.update('|'.join(normalizar_texto(x) for x in r).encode('utf-8'))
        h.update(b'\n')
    return h.hexdigest()[:12]

registros = []
for carpeta in (carpeta1, carpeta2):
    for ruta in sorted(Path(carpeta).iterdir()):
        if ruta.suffix.lower() != '.csv':
            continue
        filas, _ = leer_filas(ruta)
        for k, b in enumerate(partir_en_bloques(filas), start=1):
            i = b['encabezado'].index('Device Time')
            tiempos = [normalizar_texto(r[i]) for r in b['filas'] if i < len(r)]
            registros.append({
                'archivo': ruta.name,
                'carpeta': ruta.parent.name,
                'bloque': k,
                'linea_encabezado': b['linea'],
                'n_columnas': len(b['encabezado']),
                'n_filas': len(b['filas']),
                'primer_tiempo': tiempos[0] if tiempos else '',
                'ultimo_tiempo': tiempos[-1] if tiempos else '',
                'huella_bloque': huella_bloque(b),
            })
bloques_df = pd.DataFrame(registros)
bloques_df['veces_repetido'] = bloques_df.groupby('huella_bloque')['huella_bloque'].transform('size')

unicos = bloques_df.drop_duplicates('huella_bloque')
print(f"Bloques: {len(bloques_df)} | únicos: {len(unicos)}")
print(f"Filas en todos los bloques: {bloques_df['n_filas'].sum()} | filas únicas: {unicos['n_filas'].sum()}")

display(bloques_df[bloques_df['carpeta'].str.contains('Chiapas')].drop(columns='carpeta'))
bloques_df.to_csv(os.path.join(ruta_salida, 'bloques_archivos.csv'), index=False)

Bloques: 26 | únicos: 18
Filas en todos los bloques: 39932 | filas únicas: 30424

,archivo,bloque,linea_encabezado,n_columnas,n_filas,primer_tiempo,ultimo_tiempo,huella_bloque,veces_repetido
10,torqueTrackLog(1).csv,1,1,13,850,21-ago-2024 08:16:07.301,21-ago-2024 08:30:16.212,7539716edd3e,4
11,torqueTrackLog(1).csv,2,852,13,1947,21-ago-2024 09:21:49.824,21-ago-2024 09:54:15.817,cff80d09fcdc,3
12,torqueTrackLog(1).csv,3,2800,13,1108,21-ago-2024 12:44:25.201,21-ago-2024 13:02:52.193,a37889b90404,2
13,torqueTrackLog(2).csv,1,1,13,4,22-ago-2024 07:01:14.348,22-ago-2024 07:01:17.329,a6819c614f03,2
14,torqueTrackLog(2).csv,2,6,13,1952,22-ago-2024 07:01:38.308,22-ago-2024 07:34:09.305,97d29d37c82c,2
15,torqueTrackLog(2).csv,3,1959,17,663,24-ago-2024 14:13:27.892,24-ago-2024 14:24:29.884,0f8427f2d09b,1
16,torqueTrackLog(2).csv,4,2623,17,13,24-ago-2024 14:52:50.005,24-ago-2024 14:53:01.997,15f9daa74664,1
17,torqueTrackLog(3).csv,1,1,13,4,22-ago-2024 07:01:14.348,22-ago-2024 07:01:17.329,a6819c614f03,2
18,torqueTrackLog(3).csv,2,6,13,1952,22-ago-2024 07:01:38.308,22-ago-2024 07:34:09.305,97d29d37c82c,2
19,torqueTrackLog(4).csv,1,1,13,850,21-ago-2024 08:16:07.301,21-ago-2024 08:30:16.212,7539716edd3e,4
20,torqueTrackLog(4).csv,2,852,13,1947,21-ago-2024 09:21:49.824,21-ago-2024 09:54:15.817,cff80d09fcdc,3
21,torqueTrackLog(4).csv,3,2800,13,1108,21-ago-2024 12:44:25.201,21-ago-2024 13:02:52.193,a37889b90404,2
22,torqueTrackLog(4).csv,4,3909,13,565,22-ago-2024 06:51:29.117,22-ago-2024 07:00:53.098,19a3bed1fc43,1
23,torqueTrackLog(5).csv,1,1,13,850,21-ago-2024 08:16:07.301,21-ago-2024 08:30:16.212,7539716edd3e,4
24,torqueTrackLog(5).csv,2,852,13,1947,21-ago-2024 09:21:49.824,21-ago-2024 09:54:15.817,cff80d09fcdc,3
25,torqueTrackLog.csv,1,1,13,850,21-ago-2024 08:16:07.301,21-ago-2024 08:30:16.212,7539716edd3e,4

In [ ]:
#Celda 9

# Celda 9: catálogo de viajes únicos (un bloque por huella)
import hashlib
import json
from pathlib import Path

import pandas as pd


def huella_bloque(encabezado, filas):
    """SHA-256 del encabezado y los datos normalizados (filas rellenadas al ancho del encabezado)."""
    ancho = len(encabezado)
    filas_norm = []
    for fila in filas:
        if len(fila) > ancho:
            raise ValueError(f"Fila con {len(fila)} campos y encabezado con {ancho} columnas")
        filas_norm.append(fila + [''] * (ancho - len(fila)))
    contenido = json.dumps([encabezado, filas_norm], ensure_ascii=False, separators=(',', ':'))
    return hashlib.sha256(contenido.encode('utf-8')).hexdigest(), filas_norm


bloques_por_huella = {}
bloques_sin_filas = 0

for carpeta in (carpeta1, carpeta2):
    for ruta in sorted(Path(carpeta).iterdir()):
        # Solo CSV: el .xlsx es copia y puede alterar formatos de números y fechas
        if not ruta.is_file() or ruta.suffix.lower() != '.csv':
            continue

        filas_archivo, _ = leer_filas(ruta)

        for numero_bloque, bloque in enumerate(partir_en_bloques(filas_archivo), start=1):
            if not bloque['filas']:
                bloques_sin_filas += 1
                continue

            encabezado = [normalizar_texto(c) for c in bloque['encabezado']]
            filas = [[normalizar_texto(v) for v in fila] for fila in bloque['filas']]
            huella, filas = huella_bloque(encabezado, filas)

            if huella not in bloques_por_huella:
                i_t = encabezado.index('Device Time') if 'Device Time' in encabezado else None
                tiempos = [f[i_t] for f in filas if f[i_t]] if i_t is not None else []
                bloques_por_huella[huella] = {
                    'carpeta': ruta.parent.name,
                    'encabezado': encabezado,
                    'filas': filas,
                    'primera_fecha': tiempos[0] if tiempos else '',
                    'ultima_fecha': tiempos[-1] if tiempos else '',
                    'fuentes': [],
                }
            bloques_por_huella[huella]['fuentes'].append(
                f'{ruta.name} (bloque {numero_bloque})')

# IDs: viaje_num consecutivo (orden de aparición) + id_viaje estable derivado de la huella
ids = {h: f'V{h[:16]}' for h in bloques_por_huella}
if len(set(ids.values())) != len(ids):
    raise ValueError('Colisión en el prefijo del id_viaje; usa el SHA-256 completo.')

catalogo_viajes = pd.DataFrame([
    {
        'viaje_num': n,
        'id_viaje': ids[h],
        'carpeta': b['carpeta'],
        'n_filas': len(b['filas']),
        'n_columnas': len(b['encabezado']),
        'primera_fecha': b['primera_fecha'],
        'ultima_fecha': b['ultima_fecha'],
        'huella_bloque': h,
        'fuentes': ' | '.join(sorted(set(b['fuentes']))),
    }
    for n, (h, b) in enumerate(bloques_por_huella.items(), start=1)
])

# Datos: solo las filas de cada viaje único, con id_viaje y carpeta (el resto va en el catálogo)
partes = []
for h, b in bloques_por_huella.items():
    if 'id_viaje' in b['encabezado'] or 'carpeta' in b['encabezado']:
        raise ValueError("El archivo ya trae una columna 'id_viaje' o 'carpeta'; renómbrala primero.")
    df = pd.DataFrame(b['filas'], columns=b['encabezado'])
    df.insert(0, 'carpeta', b['carpeta'])
    df.insert(0, 'id_viaje', ids[h])
    partes.append(df)

dataset_viajes_unicos = pd.concat(partes, ignore_index=True, sort=False)

Path(ruta_salida).mkdir(parents=True, exist_ok=True)
ruta_catalogo = Path(ruta_salida) / 'viajes_unicos.csv'
ruta_dataset = Path(ruta_salida) / 'datos_viajes_unicos.csv'
catalogo_viajes.to_csv(ruta_catalogo, index=False)
dataset_viajes_unicos.to_csv(ruta_dataset, index=False)

print(f"Bloques únicos: {len(catalogo_viajes)}  (esperado: 18)")
print(f"Filas conservadas: {len(dataset_viajes_unicos)}  (esperado: 30424)")
print(f"Bloques sin filas omitidos: {bloques_sin_filas}  (esperado: 0)")
print(f"Catálogo: {ruta_catalogo}")
print(f"Datos: {ruta_dataset}")
display(catalogo_viajes.drop(columns=['huella_bloque', 'fuentes']))

Bloques únicos: 18  (esperado: 18)
Filas conservadas: 30424  (esperado: 30424)
Bloques sin filas omitidos: 0  (esperado: 0)
Catálogo: /content/drive/MyDrive/Colab Notebooks/dataset/dataset_limpio/viajes_unicos.csv
Datos: /content/drive/MyDrive/Colab Notebooks/dataset/dataset_limpio/datos_viajes_unicos.csv

,viaje_num,id_viaje,carpeta,n_filas,n_columnas,primera_fecha,ultima_fecha
0,1,V311010dca61005d2,Measurement complementary,2955,206,12-nov-2022 20:05:18.394,12-nov-2022 20:31:35.894
1,2,Vd024f5d5993be8fd,Measurement complementary,2260,206,13-nov-2022 00:08:01.613,13-nov-2022 00:26:51.113
2,3,V87d59886f08c1340,Measurement complementary,1625,206,14-nov-2022 09:31:39.429,14-nov-2022 09:45:11.421
3,4,Vc07b99ee8cd019ee,Measurement complementary,1928,99,14-nov-2022 13:02:22.085,14-nov-2022 13:18:25.584
4,5,V24eec7dea24b64cf,Measurement complementary,2957,99,16-nov-2022 09:33:04.532,16-nov-2022 10:00:16.532
5,6,V2aba46e76e9a27a6,Measurement complementary,2013,99,16-nov-2022 10:01:54.434,16-nov-2022 10:18:40.435
6,7,V4ef0ac89ad38f3e7,Measurement complementary,2787,90,10-nov.-2022 09:24:07.144,10-nov.-2022 09:47:20.141
7,8,Vcd2c56de30077c0f,Measurement complementary,3063,52,11-nov.-2022 12:47:50.319,11-nov.-2022 13:13:21.319
8,9,V6f68d543f0e1611a,Measurement complementary,2858,206,11-nov.-2022 14:56:39.138,11-nov.-2022 15:20:27.637
9,10,V61f9e23ed44f9e32,Measurement complementary,876,32,27-nov.-2022 12:44:21.062,27-nov.-2022 12:58:56.060
10,11,V2447cbc647b51f54,Mediciones Agosto 2024 Chiapas,850,13,21-ago-2024 08:16:07.301,21-ago-2024 08:30:16.212
11,12,Vbbe9541e69143406,Mediciones Agosto 2024 Chiapas,1947,13,21-ago-2024 09:21:49.824,21-ago-2024 09:54:15.817
12,13,V9a129cc0c7739508,Mediciones Agosto 2024 Chiapas,1108,13,21-ago-2024 12:44:25.201,21-ago-2024 13:02:52.193
13,14,Vd5e4d5dd8281a942,Mediciones Agosto 2024 Chiapas,4,13,22-ago-2024 07:01:14.348,22-ago-2024 07:01:17.329
14,15,V0b4c1da2b53a930b,Mediciones Agosto 2024 Chiapas,1952,13,22-ago-2024 07:01:38.308,22-ago-2024 07:34:09.305
15,16,V68c4ce039853f94b,Mediciones Agosto 2024 Chiapas,663,17,24-ago-2024 14:13:27.892,24-ago-2024 14:24:29.884
16,17,Vc9c43fa13d88123a,Mediciones Agosto 2024 Chiapas,13,17,24-ago-2024 14:52:50.005,24-ago-2024 14:53:01.997
17,18,Vdc259f3ea47cc6d8,Mediciones Agosto 2024 Chiapas,565,13,22-ago-2024 06:51:29.117,22-ago-2024 07:00:53.098

In [ ]:
#celda 10 - Inventario de columnas (E3)
print("Inventario de columnas")
from pathlib import Path
import pandas as pd

ruta_entrada = Path(ruta_salida) / "datos_viajes_unicos.csv"
df = pd.read_csv(ruta_entrada, dtype=str, keep_default_na=False)

if "id_viaje" not in df.columns:
    raise ValueError("No se encontró la columna id_viaje")

faltantes = {"", "-", "∞", "nan", "NaN"}
columnas_id = {"id_viaje", "carpeta"}
columnas_variables = [c for c in df.columns if c not in columnas_id]

# True = dato útil (el cero cuenta como dato)
utiles = df[columnas_variables].apply(lambda col: ~col.isin(faltantes))

# % de filas útiles por viaje y columna
pct_viaje = utiles.groupby(df["id_viaje"]).mean() * 100

# Carpeta de cada viaje
carpeta_viaje = df.drop_duplicates("id_viaje").set_index("id_viaje")["carpeta"]
es_chiapas = carpeta_viaje.reindex(pct_viaje.index).str.contains("Chiapas")

# Valores distintos entre las filas útiles (para detectar constantes)
n_distintos = {c: df.loc[utiles[c], c].nunique() for c in columnas_variables}

inventario = pd.DataFrame({
    "viajes_con_dato": (pct_viaje > 0).sum(),
    "viajes_measurement": (pct_viaje[~es_chiapas] > 0).sum(),
    "viajes_chiapas": (pct_viaje[es_chiapas] > 0).sum(),
    "pct_filas_util_global": (utiles.mean() * 100).round(1),
    "valores_distintos": pd.Series(n_distintos),
})
inventario["constante"] = (inventario["valores_distintos"] == 1)
inventario["sin_datos"] = (inventario["viajes_con_dato"] == 0)
inventario = (inventario.sort_values(["viajes_con_dato", "pct_filas_util_global"],
                                     ascending=False)
              .rename_axis("columna").reset_index())

inventario.to_csv(Path(ruta_salida) / "inventario_columnas.csv", index=False)

print(f"Columnas: {len(inventario)} | sin datos: {inventario['sin_datos'].sum()} | "
      f"constantes: {inventario['constante'].sum()} | "
      f"con datos y variables: {(~inventario['sin_datos'] & ~inventario['constante']).sum()}")
display(inventario[~inventario["sin_datos"]].head(40))

Inventario de columnas
Columnas: 210 | sin datos: 94 | constantes: 9 | con datos y variables: 107

,columna,viajes_con_dato,viajes_measurement,viajes_chiapas,pct_filas_util_global,valores_distintos,constante,sin_datos
0,GPS Time,18,10,8,100.0,17622,False,False
1,Device Time,18,10,8,100.0,30424,False,False
2,Longitude,18,10,8,100.0,14944,False,False
3,Latitude,18,10,8,100.0,14944,False,False
4,GPS Speed (Meters/second),18,10,8,100.0,6609,False,False
5,Horizontal Dilution of Precision,18,10,8,100.0,6872,False,False
6,Altitude,18,10,8,100.0,11888,False,False
7,Bearing,18,10,8,100.0,6754,False,False
8,G(x),18,10,8,100.0,13575,False,False
9,G(y),18,10,8,100.0,12296,False,False
10,G(z),18,10,8,100.0,15644,False,False
11,G(calibrated),18,10,8,100.0,27528,False,False
12,Acceleration Sensor(Z axis)(g),12,10,2,78.9,384,False,False
13,Engine Load(%),11,9,2,76.0,249,False,False
14,Engine RPM(rpm),11,9,2,76.0,1854,False,False
15,Acceleration Sensor(Total)(g),10,10,0,76.7,132,False,False
16,Acceleration Sensor(X axis)(g),10,10,0,76.7,231,False,False
17,Acceleration Sensor(Y axis)(g),10,10,0,76.7,217,False,False
18,Trip Time(Since journey start)(s),10,10,0,76.7,22368,False,False
19,Voltage (OBD Adapter)(V),10,10,0,76.7,33,False,False
20,GPS Latitude(°),10,10,0,76.6,9038,False,False
21,GPS Longitude(°),10,10,0,76.6,4812,False,False
22,Throttle Position(Manifold)(%),10,8,2,65.9,191,False,False
23,Absolute Throttle Position B(%),9,9,0,73.8,167,False,False
24,Average trip speed(whilst stopped or moving)(mph),9,9,0,73.8,2645,False,False
25,Barometric pressure (from vehicle)(psi),9,9,0,73.8,3,False,False
26,Catalyst Temperature (Bank 1 Sensor 1)(°F),9,9,0,73.8,1668,False,False
27,ECU(7E9): Engine Coolant Temperature(°F),9,9,0,73.8,118,False,False
28,ECU(7E9): Engine Load(%),9,9,0,73.8,324,False,False
29,ECU(7E9): Engine Load(Absolute)(%),9,9,0,73.8,503,False,False
30,ECU(7E9): Engine RPM(rpm),9,9,0,73.8,1781,False,False
31,ECU(7E9): Speed (OBD)(mph),9,9,0,73.8,193,False,False
32,ECU(7E9): Voltage (Control Module)(V),9,9,0,73.8,223,False,False
33,Engine Coolant Temperature(°F),9,9,0,73.8,75,False,False
34,Engine Load(Absolute)(%),9,9,0,73.8,302,False,False
35,Fuel Level (From Engine ECU)(%),9,9,0,73.8,60,False,False
36,GPS Accuracy(ft),9,9,0,73.8,6785,False,False
37,GPS Altitude(ft),9,9,0,73.8,10497,False,False
38,GPS vs OBD Speed difference(mph),9,9,0,73.8,2207,False,False
39,Intake Air Temperature(°F),9,9,0,73.8,42,False,False

In [ ]:
# Celda 11 -> Limpieza: de df (texto) a un dataset numérico, con unidades y nombres uniformes
MESES = {'ene': 1, 'feb': 2, 'mar': 3, 'abr': 4, 'may': 5, 'jun': 6,
         'jul': 7, 'ago': 8, 'sep': 9, 'oct': 10, 'nov': 11, 'dic': 12}

def convertir_fecha(serie):
    """'12-nov-2022 20:05:18.394' o '10-nov.-2022 09:24:07.144' -> datetime."""
    ex = serie.str.lower().str.extract(r'(\d{1,2})-([a-z]+)\.?-(\d{4})\s+(\d{2}:\d{2}:\d{2})(?:\.(\d+))?')
    mes = ex[1].map(MESES).astype('Int64').astype(str).str.zfill(2)
    texto = ex[2] + '-' + mes + '-' + ex[0].str.zfill(2) + ' ' + ex[3] + '.' + ex[4].fillna('0')
    return pd.to_datetime(texto, errors='coerce')

def fahrenheit_a_celsius(temp_f): return (temp_f - 32) * (5 / 9)
def mph_a_kmh(velocidad_mph):     return velocidad_mph * 1.609344
def psi_a_kpa(presion_psi):       return presion_psi * 6.894757
def ms_a_kmh(velocidad_ms):       return velocidad_ms * 3.6
def sin_cambio(x):                return x

conversiones = {
    'Engine RPM(rpm)':                  ('rpm', sin_cambio),
    'Engine Load(%)':                   ('carga_motor_pct', sin_cambio),
    'Engine Coolant Temperature(°F)':   ('temp_refrigerante_C', fahrenheit_a_celsius),
    'Intake Air Temperature(°F)':       ('temp_aire_admision_C', fahrenheit_a_celsius),
    'Intake Manifold Pressure(psi)':    ('presion_multiple_kPa', psi_a_kpa),
    'Throttle Position(Manifold)(%)':   ('acelerador_manifold_pct', sin_cambio),
    'Absolute Throttle Position B(%)':  ('acelerador_b_pct', sin_cambio),  # respaldo para el viaje 8
    'Air Fuel Ratio(Measured)(:1)':     ('afr', sin_cambio),
    'Speed (OBD)(mph)':                 ('velocidad_obd_kmh', mph_a_kmh),
    'Voltage (OBD Adapter)(V)':         ('voltaje_adaptador_V', sin_cambio),
    'GPS Speed (Meters/second)':        ('velocidad_gps_kmh', ms_a_kmh),
    'G(x)':                             ('g_x_ms2', sin_cambio),
    'G(y)':                             ('g_y_ms2', sin_cambio),
    'G(z)':                             ('g_z_ms2', sin_cambio),
}
# Variables del dataset (las convertidas + la aceleración total derivada)
variables_nuevas = [nuevo for nuevo, _ in conversiones.values()] + ['acel_total_ms2']

# df viene de la celda 10; catalogo_viajes, de la celda 9
assert {'id_viaje', 'carpeta', 'Device Time'} <= set(df.columns), "df no es el de la celda 10"
assert df['id_viaje'].nunique() == 18, "df no tiene los 18 viajes únicos"
faltan = [c for c in conversiones if c not in df.columns]
assert not faltan, f"Faltan columnas en df: {faltan}"

limpio = df[['id_viaje', 'carpeta', 'Device Time'] + list(conversiones)].copy()
limpio['timestamp'] = convertir_fecha(limpio['Device Time'])
assert limpio['timestamp'].notna().all(), "Hay fechas que no se pudieron convertir"

dataset = pd.DataFrame({
    'viaje_num': limpio['id_viaje'].map(catalogo_viajes.set_index('id_viaje')['viaje_num']),
    'id_viaje': limpio['id_viaje'],
    'fuente': np.where(limpio['carpeta'].str.contains('Chiapas'), 'Chiapas', 'Complementary'),
    'timestamp': limpio['timestamp'],
})
for original, (nuevo, funcion) in conversiones.items():
    # '-' y '∞' pasan a NaN (valores vacíos)
    dataset[nuevo] = funcion(pd.to_numeric(limpio[original], errors='coerce'))

# Aceleración total sin gravedad: no depende de cómo estaba colocado el teléfono
dataset['acel_total_ms2'] = (np.sqrt(dataset['g_x_ms2']**2 + dataset['g_y_ms2']**2
                                     + dataset['g_z_ms2']**2) - 9.80665)

dataset[variables_nuevas] = dataset[variables_nuevas].round(2)
dataset['tiene_motor'] = dataset.groupby('viaje_num')['rpm'].transform(lambda s: s.notna().any())

antes = len(dataset)
dataset = dataset.drop_duplicates(subset=['viaje_num', 'timestamp'])
dataset = dataset.sort_values(['viaje_num', 'timestamp']).reset_index(drop=True)
print(f"Filas: {len(dataset)} (duplicados quitados: {antes - len(dataset)}) | viajes: {dataset['viaje_num'].nunique()}")

dataset.to_csv(os.path.join(ruta_salida, 'dataset_unificado.csv'), index=False)
display(dataset.head())

Filas: 30424 (duplicados quitados: 0) | viajes: 18

,viaje_num,id_viaje,fuente,timestamp,rpm,carga_motor_pct,temp_refrigerante_C,temp_aire_admision_C,presion_multiple_kPa,acelerador_manifold_pct,acelerador_b_pct,afr,velocidad_obd_kmh,voltaje_adaptador_V,velocidad_gps_kmh,g_x_ms2,g_y_ms2,g_z_ms2,acel_total_ms2,tiene_motor
0,1,V311010dca61005d2,Complementary,2022-11-12 20:05:18.394,1187.0,40.0,54.0,49.0,61.0,21.57,21.57,14.81,0.0,13.2,0.00,-0.59,5.29,3.53,-3.42,True
1,1,V311010dca61005d2,Complementary,2022-11-12 20:05:18.896,1187.0,40.0,54.0,49.0,61.0,21.57,21.57,14.81,0.0,13.2,0.00,-1.54,2.35,10.11,0.69,True
2,1,V311010dca61005d2,Complementary,2022-11-12 20:05:19.396,1187.0,40.0,54.0,49.0,61.0,21.57,21.57,14.81,0.0,13.2,0.00,-2.19,0.50,9.60,0.06,True
3,1,V311010dca61005d2,Complementary,2022-11-12 20:05:19.895,1187.0,40.0,54.0,49.0,61.0,21.57,21.57,14.81,0.0,13.2,0.61,2.71,-0.33,10.50,1.04,True
4,1,V311010dca61005d2,Complementary,2022-11-12 20:05:20.394,1187.0,40.0,57.0,49.0,61.0,21.57,21.57,14.81,0.0,13.2,0.61,-0.42,-0.64,7.30,-2.47,True

In [ ]:
# Celda 12 -> Perfil del dataset
filas_viaje = []
for n, g in dataset.groupby('viaje_num'):
    dt = g['timestamp'].diff().dt.total_seconds()
    mediana = dt.median()
    filas_viaje.append({
        'viaje_num': n,
        'fuente': g['fuente'].iloc[0],
        'filas': len(g),
        'duracion_s': round((g['timestamp'].max() - g['timestamp'].min()).total_seconds(), 1),
        'hz': round(1 / mediana, 2) if mediana > 0 else np.nan,
        'huecos_mayores_5s': int((dt > 5).sum()),
        'mayor_hueco_s': round(dt.max(), 1),
        'timestamps_duplicados': int(g['timestamp'].duplicated().sum()),
        'tiene_motor': bool(g['tiene_motor'].iloc[0]),
    })
por_viaje = pd.DataFrame(filas_viaje)

filas_var = []
for v in variables_nuevas:
    con_dato = dataset.groupby('viaje_num')[v].apply(lambda s: s.notna().any())
    viajes = con_dato[con_dato].index
    sub = dataset.loc[dataset['viaje_num'].isin(viajes), v]
    filas_var.append({
        'variable': v,
        'viajes_con_dato': len(viajes),
        'filas_evaluadas': len(sub),
        'pct_nulos': round(100 * sub.isna().mean(), 2) if len(sub) else np.nan,
        'min': sub.min(), 'media': round(sub.mean(), 2), 'max': sub.max(),
    })
por_variable = pd.DataFrame(filas_var)

# Columnas de estado o falla (expresión corregida: ya no coincide con "Miles" ni "Acceleration")
patron = r'\bMIL\b|\bCEL\b|DTC|fault|codes? cleared|error|malfunction|warn'
estado = inventario[inventario['columna'].str.contains(patron, case=False, regex=True)
                    & ~inventario['sin_datos']]

print(f"1. Filas: {len(dataset)} en {dataset['viaje_num'].nunique()} viajes")
print(f"3. Fechas válidas: {dataset['timestamp'].notna().sum()} de {len(dataset)}")
print("   Viajes: filas, muestreo, huecos y duplicados:")
display(por_viaje)
print("\nVariables: nulos y rangos (°C, km/h, kPa, m/s²):")
display(por_variable)
print("\nColumnas de estado, falla o error que sí traen datos:")
display(estado[['columna', 'viajes_con_dato', 'pct_filas_util_global', 'valores_distintos', 'constante']])

por_viaje.to_csv(os.path.join(ruta_salida, 'perfil_viajes.csv'), index=False)
por_variable.to_csv(os.path.join(ruta_salida, 'perfil_variables.csv'), index=False)

1. Filas: 30424 en 18 viajes
3. Fechas válidas: 30424 de 30424
   Viajes: filas, muestreo, huecos y duplicados:

,viaje_num,fuente,filas,duracion_s,hz,huecos_mayores_5s,mayor_hueco_s,timestamps_duplicados,tiene_motor
0,1,Complementary,2955,1577.5,2.0,2,88.0,0,True
1,2,Complementary,2260,1129.5,2.0,0,0.5,0,True
2,3,Complementary,1625,812.0,2.0,0,0.5,0,True
3,4,Complementary,1928,963.5,2.0,0,0.5,0,True
4,5,Complementary,2957,1632.0,2.0,1,154.5,0,True
5,6,Complementary,2013,1006.0,2.0,0,0.5,0,True
6,7,Complementary,2787,1393.0,2.0,0,0.5,0,True
7,8,Complementary,3063,1531.0,2.0,0,0.5,0,True
8,9,Complementary,2858,1428.5,2.0,0,0.5,0,True
9,10,Complementary,876,875.0,1.0,0,1.0,0,False
10,11,Chiapas,850,848.9,1.0,0,1.0,0,False
11,12,Chiapas,1947,1946.0,1.0,0,1.2,0,False
12,13,Chiapas,1108,1107.0,1.0,0,1.0,0,False
13,14,Chiapas,4,3.0,1.0,0,1.0,0,False
14,15,Chiapas,1952,1951.0,1.0,13,22.4,0,False
15,16,Chiapas,663,662.0,1.0,0,1.0,0,True
16,17,Chiapas,13,12.0,1.0,0,1.0,0,True
17,18,Chiapas,565,564.0,1.0,0,1.0,0,False

Variables: nulos y rangos (°C, km/h, kPa, m/s²):

,variable,viajes_con_dato,filas_evaluadas,pct_nulos,min,media,max
0,rpm,11,23122,0.00,0.00,1385.42,5741.50
1,carga_motor_pct,11,23122,0.00,0.00,22.84,90.98
2,temp_refrigerante_C,9,22446,0.01,21.00,89.39,102.00
3,temp_aire_admision_C,9,22446,0.02,19.00,41.48,60.00
4,presion_multiple_kPa,9,22446,0.02,18.00,52.33,190.00
5,acelerador_manifold_pct,10,20059,0.00,10.20,26.27,88.63
6,acelerador_b_pct,9,22446,0.00,10.98,26.68,88.63
7,afr,9,22446,0.12,11.73,17.92,29.38
8,velocidad_obd_kmh,9,22446,0.00,0.00,29.81,111.00
9,voltaje_adaptador_V,10,23322,0.00,11.00,13.27,14.60
10,velocidad_gps_kmh,18,30424,0.00,0.00,28.35,112.97
11,g_x_ms2,18,30424,0.00,-18.54,-1.19,16.21
12,g_y_ms2,18,30424,0.00,-9.69,5.96,19.57
13,g_z_ms2,18,30424,0.00,-14.56,3.32,17.37
14,acel_total_ms2,18,30424,0.00,-8.60,0.06,12.67

Columnas de estado, falla o error que sí traen datos:

,columna,viajes_con_dato,pct_filas_util_global,valores_distintos,constante
64,Distance travelled since codes cleared(miles),8,63.7,89,False
83,ECU(7E9): Distance travelled since codes clear...,7,54.5,67,False
99,Distance travelled with MIL/CEL lit(miles),5,41.0,1,True

In [ ]:
#Celda 13
import pandas as pd
import numpy as np
import os

TIEMPO_RECORTE_SEG = 10    # supuesto: se descartan los primeros segundos de cada viaje
HUECO_MAX_SEG = 5          # un salto mayor parte el viaje en otro segmento
RANGO_INTERPOLACION = 3    # máximo de muestras vacías consecutivas que se rellenan
DURACION_MINIMA_SEG = 30   # segmentos más cortos se descartan

ruta_dataset = os.path.join(ruta_salida, 'dataset_unificado.csv')
df_raw = pd.read_csv(ruta_dataset, parse_dates=['timestamp'])

columnas_meta = ['viaje_num', 'id_viaje', 'fuente', 'tiene_motor', 'segmento_id']
columnas_num = [c for c in df_raw.columns if c not in columnas_meta + ['timestamp']]

# 1. Recorte inicial de cada viaje
inicio = df_raw.groupby('viaje_num')['timestamp'].transform('min')
df_recorte = df_raw[df_raw['timestamp'] >= inicio + pd.Timedelta(seconds=TIEMPO_RECORTE_SEG)].copy()
print(f"Filas: {len(df_raw)} -> {len(df_recorte)} (quitadas: {len(df_raw) - len(df_recorte)})")

# 2. Segmentos: un salto mayor a HUECO_MAX_SEG abre un segmento nuevo
df_recorte = df_recorte.sort_values(['viaje_num', 'timestamp']).reset_index(drop=True)
dt = df_recorte.groupby('viaje_num')['timestamp'].diff().dt.total_seconds()
salto = (dt > HUECO_MAX_SEG) | dt.isna()
df_recorte['segmento_id'] = salto.groupby(df_recorte['viaje_num']).cumsum()

# 3. Remuestreo a 1 Hz: promedio de lo que cae en cada segundo
df_recorte['timestamp_1s'] = df_recorte['timestamp'].dt.floor('1s')
df_1hz = (df_recorte.groupby(columnas_meta + ['timestamp_1s'])[columnas_num].mean()
          .reset_index().rename(columns={'timestamp_1s': 'timestamp'}))

# 4. Interpolación de vacíos cortos, segmento por segmento
partes = []
for (viaje, seg), g in df_1hz.groupby(['viaje_num', 'segmento_id']):
    meta = g.iloc[0][columnas_meta]           # los metadatos son constantes dentro del segmento
    g = g.set_index('timestamp').resample('1s').asfreq()
    for c in columnas_meta:
        g[c] = meta[c]
    g[columnas_num] = g[columnas_num].interpolate(method='linear', limit=RANGO_INTERPOLACION)
    partes.append(g.reset_index())
df_interpolado = pd.concat(partes, ignore_index=True)
df_interpolado['tiene_motor'] = df_interpolado['tiene_motor'].astype(bool)
df_interpolado[['viaje_num', 'segmento_id']] = df_interpolado[['viaje_num', 'segmento_id']].astype(int)

# 5. Descartar segmentos cortos (a 1 Hz, filas = segundos)
filas_seg = df_interpolado.groupby(['viaje_num', 'segmento_id'])['timestamp'].transform('size')
df_final = df_interpolado[filas_seg >= DURACION_MINIMA_SEG].copy()
df_final[columnas_num] = df_final[columnas_num].round(2)

# Guardar y reportar
df_final.to_csv(os.path.join(ruta_salida, 'dataset_1hz.csv'), index=False)

print(f"\nFilas finales: {len(df_final)} | viajes: {df_final['viaje_num'].nunique()} | "
      f"segmentos: {df_final.groupby(['viaje_num', 'segmento_id']).ngroups}")
resumen = df_final.groupby('viaje_num').agg(filas=('timestamp', 'size'),
                                            segmentos=('segmento_id', 'nunique'))
resumen['segmento_mas_largo_s'] = (df_final.groupby(['viaje_num', 'segmento_id']).size()
                                   .groupby('viaje_num').max())
display(resumen)
print("\nVacíos que quedaron en viajes con motor:")
print(df_final.loc[df_final['tiene_motor'], ['rpm', 'carga_motor_pct']].isna().sum())

Filas: 30424 -> 30148 (quitadas: 276)

Filas finales: 18815 | viajes: 16 | segmentos: 20

           filas  segmentos  segmento_mas_largo_s
viaje_num
1           1469          3                   861
2           1120          1                  1120
3            803          1                   803
4            954          1                   954
5           1468          2                   919
6            997          1                   997
7           1384          1                  1384
8           1522          1                  1522
9           1419          1                  1419
10           865          1                   865
11           839          1                   839
12          1936          1                  1936
13          1097          1                  1097
15          1736          2                  1702
16           652          1                   652
18           554          1                   554

Vacíos que quedaron en viajes con motor:
rpm                0
carga_motor_pct    0
dtype: int64

In [ ]:
#Celda 14 -> División por viaje

In [ ]:
#Celda 15 -> Normalización

In [ ]:
#Celda 16

In [ ]:
#Celda 17

In [ ]:
#Celda 18