<a href="https://colab.research.google.com/github/AlfCR/dnn-estadia/blob/main/dnn_estadia_ACP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# LSTM y GRU en el mantenimiento predictivo de entornos vehiculares

## 1. Configuración Inicial y Verificación de Entorno

### Clonación del Repositorio y Configuración del Directorio

In [1]:
#Celda 1
import os
if not os.path.exists('/content/dnn-estadia'):
    !git clone https://github.com/AlfCR/dnn-estadia.git
%cd /content/dnn-estadia

Cloning into 'dnn-estadia'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 9 (delta 1), reused 3 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (9/9), 11.41 KiB | 417.00 KiB/s, done.
Resolving deltas: 100% (1/1), done.
/content/dnn-estadia

### Verificación de Versiones de Frameworks de Aprendizaje Automático

In [ ]:
#Celda 2
#Verificación de disponibilidad y versión  de TensorFlow
import tensorflow as tf
print(tf.__version__)
print(tf.config.list_physical_devices('GPU'))

2.20.0
[]

In [ ]:
#Celda 3
#Verificación de  disponibilidad y versión  PyTorch
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.11.0+cpu
False


Observación: Eliminar
1) Indentificación de espacióis en el encabezado de la columna
2) Objetivo: si uno estos 10 archivos en un solo dataframe, ¿qué columnas me conviene conservar?
3) Intersección (20) = las columnas que SÍ están presentes en absolutamente todos los archivos
4) Unión (212) = todas las columnas que existen en al menos un archivo

**Nota: ** La norma para identificar las variables a usar bajo la norma SAE J1979 con las que se debe de implementar para el mantenimiento preventivo son las: {Identificar que variables van para esa normativa}-> implementar el mantenimiento predictivo.

Configuración para rutas

In [2]:
# Celda 4
import os
import re
import numpy as np
import pandas as pd
import hashlib
import shutil

from google.colab import drive
drive.mount('/content/drive')

# Configuración de rutas
base = '/content/drive/MyDrive/Colab Notebooks/dataset'
carpeta1 = os.path.join(base, 'Measurement complementary')
carpeta2 = os.path.join(base, 'Mediciones Agosto 2024 Chiapas')
ruta_salida = os.path.join(base, 'dataset_limpio')

# Ruta de respado de las carpetas orignales
respaldo_dataset = os.path.join(base, 'respaldo_carpetas')

# Carpeta de salida
os.makedirs(ruta_salida, exist_ok=True)

# Validación de existencia de las carpetas
for i in (carpeta1, carpeta2):
    assert os.path.isdir(i), f"La carpeta {i} no existe"
    print(f"{os.path.basename(i)}: {len(os.listdir(i))} archivos")

for origen in (carpeta1, carpeta2):
    destino = os.path.join(respaldo_dataset, os.path.basename(origen))
    if os.path.exists(destino):
       print(f"Respado existente: {destino}")
    else:
        shutil.copytree(origen, destino)
        print(f"Respado creado: {destino}")

    # Verificación: mismos archivos y mismos tamaños
    tam_origen = {f: os.path.getsize(os.path.join(origen, f)) for f in os.listdir(origen)}
    tam_destino = {f: os.path.getsize(os.path.join(destino, f)) for f in os.listdir(destino)}

    assert tam_origen == tam_destino, f"El respado de {origen} no coincide con el original"
    print(f" Verificado: {len(tam_origen)} archivos con el mismo tamaño")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Measurement complementary: 11 archivos
Mediciones Agosto 2024 Chiapas: 6 archivos
Respado existente: /content/drive/MyDrive/Colab Notebooks/dataset/respaldo_carpetas/Measurement complementary
 Verificado: 11 archivos con el mismo tamaño
Respado existente: /content/drive/MyDrive/Colab Notebooks/dataset/respaldo_carpetas/Mediciones Agosto 2024 Chiapas
 Verificado: 6 archivos con el mismo tamaño

In [3]:
# Celda 5: huellas SHA-256 de originales y respaldo
def calcular_sha256(ruta):
    h = hashlib.sha256()
    with open(ruta, 'rb') as f:
        # 1024 * 1024 para leer en bloques de 1 MB
        for bloque in iter(lambda: f.read(1024 * 1024), b''):
            h.update(bloque)
    return h.hexdigest()

filas = []
for carpeta in (carpeta1, carpeta2):
    nombre_carpeta = os.path.basename(carpeta)
    for nombre in sorted(os.listdir(carpeta)):
        ruta_original = os.path.join(carpeta, nombre)
        ruta_respaldo = os.path.join(respaldo_dataset, nombre_carpeta, nombre)
        filas.append({
            'carpeta': nombre_carpeta,
            'archivo': nombre,
            'tamano_kb': round(os.path.getsize(ruta_original) / 1024, 1),
            'sha256_original': calcular_sha256(ruta_original),
            'sha256_respaldo': calcular_sha256(ruta_respaldo),
        })

huellas = pd.DataFrame(filas)

# El respaldo debe ser idéntico al original
assert (huellas['sha256_original'] == huellas['sha256_respaldo']).all(), \
    "Hay archivos distintos entre el original y el respaldo"
print(f"Respaldo idéntico al original: {len(huellas)} archivos")

# Línea base: se guarda solo la primera vez; después, se compara contra ella
destino_huellas = os.path.join(ruta_salida, 'huellas_originales.csv')
if os.path.exists(destino_huellas):
    base_previa = pd.read_csv(destino_huellas)
    comp = huellas.merge(
        base_previa[['carpeta', 'archivo', 'sha256_original']],
        on=['carpeta', 'archivo'], how='outer', suffixes=('_hoy', '_base'))
    cambios = comp[comp['sha256_original_hoy'] != comp['sha256_original_base']]
    if cambios.empty:
        print("Los originales siguen idénticos a la línea base.")
    else:
        print(f"ATENCIÓN: archivos distintos o faltantes:\n{cambios}")
else:
    huellas.to_csv(destino_huellas, index=False)
    print(f"Línea base guardada en: {destino_huellas}")

# Vista corta (huella recortada a 12 caracteres)
huellas[['carpeta', 'archivo', 'tamano_kb']].assign(sha256=huellas['sha256_original'].str[:12])

Respaldo idéntico al original: 17 archivos
Los originales siguen idénticos a la línea base.

,carpeta,archivo,tamano_kb,sha256
0,Measurement complementary,trackLog-2022-nov-12_20-05-07.csv,3688.4,0a710f3e0d41
1,Measurement complementary,trackLog-2022-nov-13_00-03-52.csv,2893.0,2c3cdb0be236
2,Measurement complementary,trackLog-2022-nov-14_09-03-16.csv,2059.9,79633a18a410
3,Measurement complementary,trackLog-2022-nov-14_13-01-38.csv,1997.6,c51719174c03
4,Measurement complementary,trackLog-2022-nov-16_09-32-26.csv,2985.9,b49a45fc627b
5,Measurement complementary,trackLog-2022-nov-16_09-44-58.csv,2077.3,c7abe127ff57
6,Measurement complementary,trackLog-2022-nov-16_09-44-58.xlsx,1061.5,7532cf91c3d1
7,Measurement complementary,trackLog-2022-nov.-10_09-23-59 (1).csv,2539.3,9759ceee4913
8,Measurement complementary,trackLog-2022-nov.-11_12-47-43.csv,1760.4,5cce8384939b
9,Measurement complementary,trackLog-2022-nov.-11_14-46-26.csv,3585.9,ac8839f24405
10,Measurement complementary,trackLog-2022-nov.-27_12-43-04.csv,338.4,d3e3db59eed1
11,Mediciones Agosto 2024 Chiapas,torqueTrackLog(1).csv,604.1,85a55c14d9d4
12,Mediciones Agosto 2024 Chiapas,torqueTrackLog(2).csv,438.1,804a62f4ce0b
13,Mediciones Agosto 2024 Chiapas,torqueTrackLog(3).csv,296.4,038a441604cc
14,Mediciones Agosto 2024 Chiapas,torqueTrackLog(4).csv,691.5,57695bfa9b6e
15,Mediciones Agosto 2024 Chiapas,torqueTrackLog(5).csv,432.6,ed8f11de44b8
16,Mediciones Agosto 2024 Chiapas,torqueTrackLog.csv,130.8,d9d25be859f1

In [4]:
#Celda 6 - Confirmar la línea base
base_previa = pd.read_csv(destino_huellas)

actual = pd.DataFrame([
    {'carpeta': os.path.basename(c), 'archivo': n,
     'sha256_original': calcular_sha256(os.path.join(c, n))}
    for c in (carpeta1, carpeta2) for n in sorted(os.listdir(c))
])

comparacion = actual.merge(
    base_previa[['carpeta', 'archivo', 'sha256_original']],
    on=['carpeta', 'archivo'], how='outer',
    suffixes=('_actual', '_base'), indicator=True)

coinciden = (comparacion['_merge'].eq('both')
             & comparacion['sha256_original_actual'].eq(comparacion['sha256_original_base']))
assert coinciden.all(), "La lista o el contenido de los originales cambió respecto a la línea base."
print("Integridad verificada: originales idénticos a la línea base.")

Integridad verificada: originales idénticos a la línea base.

In [5]:
# Celda 7: Auditar contenido y formato (por bloques de encabezado)
import csv
import io
from pathlib import Path

FALTANTES = {'', '-', '∞' ,'nan', 'NaN'}

def normalizar_texto(valor):
    if pd.isna(valor):
        return ''
    return str(valor).replace('\u00a0', ' ').strip()

def leer_filas(ruta):
    """Devuelve las filas como listas de texto, sin que pandas decida el ancho."""
    if ruta.suffix.lower() == '.xlsx':
        bruto = pd.read_excel(ruta, header=None, dtype='string', keep_default_na=False)
        return bruto.fillna('').values.tolist(), 'xlsx: primera hoja'
    for cod in ('utf-8-sig', 'cp1252'):
        try:
            with open(ruta, 'r', encoding=cod, newline='') as f:
                texto = f.read()
            break
        except UnicodeDecodeError:
            continue
    else:
        raise ValueError('No se pudo determinar la codificación del CSV.')
    try:
        sep = csv.Sniffer().sniff(texto[:8192], delimiters=',;\t|').delimiter
    except csv.Error:
        sep = ','
    filas = list(csv.reader(io.StringIO(texto, newline=''), delimiter=sep))
    return filas, f'csv: separador={sep!r}, encoding={cod}'

def partir_en_bloques(filas):
    """Un bloque = un encabezado (el primero o uno repetido) y las filas que le siguen."""
    pares = [(n, f) for n, f in enumerate(filas, start=1)
             if any(normalizar_texto(x) for x in f)]          # sin líneas en blanco
    if not pares:
        return []
    primer_campo = normalizar_texto(pares[0][1][0])
    bloques = []
    for n, fila in pares:
        if normalizar_texto(fila[0]) == primer_campo:
            bloques.append({'linea': n,
                            'encabezado': [normalizar_texto(x) for x in fila],
                            'filas': []})
        else:
            bloques[-1]['filas'].append(fila)
    return bloques

def auditar_bloques(bloques):
    vacia_por_columna = {}
    for b in bloques:
        for i, nombre in enumerate(b['encabezado']):
            etiqueta = nombre or f'__SIN_NOMBRE_{i + 1}'
            vacia = all((normalizar_texto(r[i]) in FALTANTES) if i < len(r) else True
                        for r in b['filas'])
            vacia_por_columna.setdefault(etiqueta, []).append(vacia)
    columnas = {n for n in vacia_por_columna if not n.startswith('__SIN_NOMBRE_')}
    vacias = sorted(n for n, v in vacia_por_columna.items() if all(v))
    duplicadas = sorted({n for b in bloques for n in b['encabezado']
                         if n and b['encabezado'].count(n) > 1})
    return columnas, vacias, duplicadas

esquemas, filas_reporte = {}, []
for carpeta in (carpeta1, carpeta2):
    for ruta in sorted(Path(carpeta).iterdir()):
        if (not ruta.is_file() or ruta.name.startswith('~$')
                or ruta.suffix.lower() not in ('.csv', '.xlsx')):
            continue
        clave = f'{ruta.parent.name}/{ruta.name}'
        try:
            filas, detalle = leer_filas(ruta)
            bloques = partir_en_bloques(filas)
            columnas, vacias, duplicadas = auditar_bloques(bloques)
            esquemas[clave] = columnas
            filas_reporte.append({
                'archivo': clave,
                'filas_datos': sum(len(b['filas']) for b in bloques),
                'n_bloques': len(bloques),
                'lineas_encabezado_repetido': [b['linea'] for b in bloques[1:]],
                'n_esquemas_distintos': len({tuple(b['encabezado']) for b in bloques}),
                'n_columnas': len(columnas),
                'columnas_duplicadas': duplicadas,
                'columnas_vacias': vacias,
                'lectura': detalle,
                'error': '',
            })
        except Exception as error:
            filas_reporte.append({'archivo': clave, 'error': str(error)})

# Columnas que le faltan a cada archivo respecto a la unión de SU carpeta (solo el conteo)
union_carpeta = {}
for clave, cols in esquemas.items():
    union_carpeta.setdefault(clave.split('/')[0], set()).update(cols)
for fila in filas_reporte:
    if fila['archivo'] in esquemas:
        nombre_carpeta = fila['archivo'].split('/')[0]
        fila['n_faltantes_vs_carpeta'] = len(union_carpeta[nombre_carpeta] - esquemas[fila['archivo']])

auditoria = pd.DataFrame(filas_reporte)
display(auditoria.drop(columns=['lectura']))

ruta_auditoria = os.path.join(ruta_salida, 'auditoria_archivos.csv')
auditoria.to_csv(ruta_auditoria, index=False)
print(f'Auditoría guardada en: {ruta_auditoria}')

,archivo,filas_datos,n_bloques,lineas_encabezado_repetido,n_esquemas_distintos,n_columnas,columnas_duplicadas,columnas_vacias,error,n_faltantes_vs_carpeta
0,Measurement complementary/trackLog-2022-nov-12...,2955,1,[],1,206,[],"[0-100kph Time(s), 0-100mph Time(s), 0-200kph ...",,3
1,Measurement complementary/trackLog-2022-nov-13...,2260,1,[],1,206,[],"[0-100kph Time(s), 0-100mph Time(s), 0-200kph ...",,3
2,Measurement complementary/trackLog-2022-nov-14...,1625,1,[],1,206,[],"[0-100kph Time(s), 0-100mph Time(s), 0-200kph ...",,3
3,Measurement complementary/trackLog-2022-nov-14...,1928,1,[],1,99,[],[Alcohol Fuel Percentage(%)],,110
4,Measurement complementary/trackLog-2022-nov-16...,2957,1,[],1,99,[],"[Alcohol Fuel Percentage(%), Boost Pressure Se...",,110
5,Measurement complementary/trackLog-2022-nov-16...,2013,1,[],1,99,[],"[Alcohol Fuel Percentage(%), Boost Pressure Se...",,110
6,Measurement complementary/trackLog-2022-nov-16...,2013,1,[],1,99,[],"[Alcohol Fuel Percentage(%), Boost Pressure Se...",,110
7,Measurement complementary/trackLog-2022-nov.-1...,2787,1,[],1,90,[],"[Engine kW (At the wheels)(kW), Fuel trim Bank...",,119
8,Measurement complementary/trackLog-2022-nov.-1...,3063,1,[],1,52,[],[],,157
9,Measurement complementary/trackLog-2022-nov.-1...,2858,1,[],1,206,[],"[0-100kph Time(s), 0-100mph Time(s), 0-200kph ...",,3
10,Measurement complementary/trackLog-2022-nov.-2...,876,1,[],1,32,[],[],,177
11,Mediciones Agosto 2024 Chiapas/torqueTrackLog(...,3905,3,"[852, 2800]",1,12,[],[__SIN_NOMBRE_13],,5
12,Mediciones Agosto 2024 Chiapas/torqueTrackLog(...,2632,4,"[6, 1959, 2623]",2,17,[],[__SIN_NOMBRE_13],,0
13,Mediciones Agosto 2024 Chiapas/torqueTrackLog(...,1956,2,[6],1,12,[],[__SIN_NOMBRE_13],,5
14,Mediciones Agosto 2024 Chiapas/torqueTrackLog(...,4470,4,"[852, 2800, 3909]",1,12,[],[__SIN_NOMBRE_13],,5
15,Mediciones Agosto 2024 Chiapas/torqueTrackLog(...,2797,2,[852],1,12,[],[__SIN_NOMBRE_13],,5
16,Mediciones Agosto 2024 Chiapas/torqueTrackLog.csv,850,1,[],1,12,[],[__SIN_NOMBRE_13],,5

Auditoría guardada en: /content/drive/MyDrive/Colab Notebooks/dataset/dataset_limpio/auditoria_archivos.csv

In [7]:
# Celda 8: detalle por bloque
registros = []
for carpeta in (carpeta1, carpeta2):
    for ruta in sorted(Path(carpeta).iterdir()):
        if ruta.suffix.lower() != '.csv':
            continue
        filas, _ = leer_filas(ruta)
        for k, b in enumerate(partir_en_bloques(filas), start=1):
            i = b['encabezado'].index('Device Time')
            tiempos = [normalizar_texto(r[i]) for r in b['filas'] if i < len(r)]
            registros.append({
                'archivo': f'{ruta.parent.name}/{ruta.name}',
                'bloque': k,
                'linea_encabezado': b['linea'],
                'n_columnas': len(b['encabezado']),
                'n_filas': len(b['filas']),
                'primer_tiempo': tiempos[0] if tiempos else '',
                'ultimo_tiempo': tiempos[-1] if tiempos else '',
            })
bloques_df = pd.DataFrame(registros)
display(bloques_df[bloques_df['archivo'].str.contains('Chiapas')])
bloques_df.to_csv(os.path.join(ruta_salida, 'bloques_archivos.csv'), index=False)

,archivo,bloque,linea_encabezado,n_columnas,n_filas,primer_tiempo,ultimo_tiempo
10,Mediciones Agosto 2024 Chiapas/torqueTrackLog(...,1,1,13,850,21-ago-2024 08:16:07.301,21-ago-2024 08:30:16.212
11,Mediciones Agosto 2024 Chiapas/torqueTrackLog(...,2,852,13,1947,21-ago-2024 09:21:49.824,21-ago-2024 09:54:15.817
12,Mediciones Agosto 2024 Chiapas/torqueTrackLog(...,3,2800,13,1108,21-ago-2024 12:44:25.201,21-ago-2024 13:02:52.193
13,Mediciones Agosto 2024 Chiapas/torqueTrackLog(...,1,1,13,4,22-ago-2024 07:01:14.348,22-ago-2024 07:01:17.329
14,Mediciones Agosto 2024 Chiapas/torqueTrackLog(...,2,6,13,1952,22-ago-2024 07:01:38.308,22-ago-2024 07:34:09.305
15,Mediciones Agosto 2024 Chiapas/torqueTrackLog(...,3,1959,17,663,24-ago-2024 14:13:27.892,24-ago-2024 14:24:29.884
16,Mediciones Agosto 2024 Chiapas/torqueTrackLog(...,4,2623,17,13,24-ago-2024 14:52:50.005,24-ago-2024 14:53:01.997
17,Mediciones Agosto 2024 Chiapas/torqueTrackLog(...,1,1,13,4,22-ago-2024 07:01:14.348,22-ago-2024 07:01:17.329
18,Mediciones Agosto 2024 Chiapas/torqueTrackLog(...,2,6,13,1952,22-ago-2024 07:01:38.308,22-ago-2024 07:34:09.305
19,Mediciones Agosto 2024 Chiapas/torqueTrackLog(...,1,1,13,850,21-ago-2024 08:16:07.301,21-ago-2024 08:30:16.212
20,Mediciones Agosto 2024 Chiapas/torqueTrackLog(...,2,852,13,1947,21-ago-2024 09:21:49.824,21-ago-2024 09:54:15.817
21,Mediciones Agosto 2024 Chiapas/torqueTrackLog(...,3,2800,13,1108,21-ago-2024 12:44:25.201,21-ago-2024 13:02:52.193
22,Mediciones Agosto 2024 Chiapas/torqueTrackLog(...,4,3909,13,565,22-ago-2024 06:51:29.117,22-ago-2024 07:00:53.098
23,Mediciones Agosto 2024 Chiapas/torqueTrackLog(...,1,1,13,850,21-ago-2024 08:16:07.301,21-ago-2024 08:30:16.212
24,Mediciones Agosto 2024 Chiapas/torqueTrackLog(...,2,852,13,1947,21-ago-2024 09:21:49.824,21-ago-2024 09:54:15.817
25,Mediciones Agosto 2024 Chiapas/torqueTrackLog.csv,1,1,13,850,21-ago-2024 08:16:07.301,21-ago-2024 08:30:16.212

In [6]:
# Celda 8: detalle por bloque
import hashlib

def huella_bloque(b):
    h = hashlib.sha256()
    for r in b['filas']:
        h.update('|'.join(normalizar_texto(x) for x in r).encode('utf-8'))
        h.update(b'\n')
    return h.hexdigest()[:12]

registros = []
for carpeta in (carpeta1, carpeta2):
    for ruta in sorted(Path(carpeta).iterdir()):
        if ruta.suffix.lower() != '.csv':
            continue
        filas, _ = leer_filas(ruta)
        for k, b in enumerate(partir_en_bloques(filas), start=1):
            i = b['encabezado'].index('Device Time')
            tiempos = [normalizar_texto(r[i]) for r in b['filas'] if i < len(r)]
            registros.append({
                'archivo': ruta.name,
                'carpeta': ruta.parent.name,
                'bloque': k,
                'linea_encabezado': b['linea'],
                'n_columnas': len(b['encabezado']),
                'n_filas': len(b['filas']),
                'primer_tiempo': tiempos[0] if tiempos else '',
                'ultimo_tiempo': tiempos[-1] if tiempos else '',
                'huella_bloque': huella_bloque(b),
            })
bloques_df = pd.DataFrame(registros)
bloques_df['veces_repetido'] = bloques_df.groupby('huella_bloque')['huella_bloque'].transform('size')

unicos = bloques_df.drop_duplicates('huella_bloque')
print(f"Bloques: {len(bloques_df)} | únicos: {len(unicos)}")
print(f"Filas en todos los bloques: {bloques_df['n_filas'].sum()} | filas únicas: {unicos['n_filas'].sum()}")

display(bloques_df[bloques_df['carpeta'].str.contains('Chiapas')].drop(columns='carpeta'))
bloques_df.to_csv(os.path.join(ruta_salida, 'bloques_archivos.csv'), index=False)

Bloques: 26 | únicos: 18
Filas en todos los bloques: 39932 | filas únicas: 30424

,archivo,bloque,linea_encabezado,n_columnas,n_filas,primer_tiempo,ultimo_tiempo,huella_bloque,veces_repetido
10,torqueTrackLog(1).csv,1,1,13,850,21-ago-2024 08:16:07.301,21-ago-2024 08:30:16.212,7539716edd3e,4
11,torqueTrackLog(1).csv,2,852,13,1947,21-ago-2024 09:21:49.824,21-ago-2024 09:54:15.817,cff80d09fcdc,3
12,torqueTrackLog(1).csv,3,2800,13,1108,21-ago-2024 12:44:25.201,21-ago-2024 13:02:52.193,a37889b90404,2
13,torqueTrackLog(2).csv,1,1,13,4,22-ago-2024 07:01:14.348,22-ago-2024 07:01:17.329,a6819c614f03,2
14,torqueTrackLog(2).csv,2,6,13,1952,22-ago-2024 07:01:38.308,22-ago-2024 07:34:09.305,97d29d37c82c,2
15,torqueTrackLog(2).csv,3,1959,17,663,24-ago-2024 14:13:27.892,24-ago-2024 14:24:29.884,0f8427f2d09b,1
16,torqueTrackLog(2).csv,4,2623,17,13,24-ago-2024 14:52:50.005,24-ago-2024 14:53:01.997,15f9daa74664,1
17,torqueTrackLog(3).csv,1,1,13,4,22-ago-2024 07:01:14.348,22-ago-2024 07:01:17.329,a6819c614f03,2
18,torqueTrackLog(3).csv,2,6,13,1952,22-ago-2024 07:01:38.308,22-ago-2024 07:34:09.305,97d29d37c82c,2
19,torqueTrackLog(4).csv,1,1,13,850,21-ago-2024 08:16:07.301,21-ago-2024 08:30:16.212,7539716edd3e,4
20,torqueTrackLog(4).csv,2,852,13,1947,21-ago-2024 09:21:49.824,21-ago-2024 09:54:15.817,cff80d09fcdc,3
21,torqueTrackLog(4).csv,3,2800,13,1108,21-ago-2024 12:44:25.201,21-ago-2024 13:02:52.193,a37889b90404,2
22,torqueTrackLog(4).csv,4,3909,13,565,22-ago-2024 06:51:29.117,22-ago-2024 07:00:53.098,19a3bed1fc43,1
23,torqueTrackLog(5).csv,1,1,13,850,21-ago-2024 08:16:07.301,21-ago-2024 08:30:16.212,7539716edd3e,4
24,torqueTrackLog(5).csv,2,852,13,1947,21-ago-2024 09:21:49.824,21-ago-2024 09:54:15.817,cff80d09fcdc,3
25,torqueTrackLog.csv,1,1,13,850,21-ago-2024 08:16:07.301,21-ago-2024 08:30:16.212,7539716edd3e,4

In [8]:
#Archivos en cada sesíon
bloques_df.groupby('huella_bloque').agg(
    veces=('archivo', 'size'),
    n_filas=('n_filas', 'first'),
    archivos=('archivo', lambda s: ' | '.join(sorted(s))),
).sort_values('veces', ascending=False)

,veces,n_filas,archivos
huella_bloque,,,
7539716edd3e,4,850,torqueTrackLog(1).csv | torqueTrackLog(4).csv ...
cff80d09fcdc,3,1947,torqueTrackLog(1).csv | torqueTrackLog(4).csv ...
a6819c614f03,2,4,torqueTrackLog(2).csv | torqueTrackLog(3).csv
a37889b90404,2,1108,torqueTrackLog(1).csv | torqueTrackLog(4).csv
97d29d37c82c,2,1952,torqueTrackLog(2).csv | torqueTrackLog(3).csv
051e4a48fb60,1,2787,trackLog-2022-nov.-10_09-23-59 (1).csv
0f8427f2d09b,1,663,torqueTrackLog(2).csv
15f9daa74664,1,13,torqueTrackLog(2).csv
2342f37b4451,1,2260,trackLog-2022-nov-13_00-03-52.csv
19a3bed1fc43,1,565,torqueTrackLog(4).csv
6d2ec8a6c3ac,1,2858,trackLog-2022-nov.-11_14-46-26.csv
64180187616d,1,876,trackLog-2022-nov.-27_12-43-04.csv
42aead3fbd5a,1,2957,trackLog-2022-nov-16_09-32-26.csv
3c578b6e0dee,1,1625,trackLog-2022-nov-14_09-03-16.csv
2a2aee26418d,1,2013,trackLog-2022-nov-16_09-44-58.csv
85cb53bf15dc,1,2955,trackLog-2022-nov-12_20-05-07.csv
aebd080a48a8,1,1928,trackLog-2022-nov-14_13-01-38.csv
e82ca1d94502,1,3063,trackLog-2022-nov.-11_12-47-43.csv

In [9]:
#Celda 9 -> Busqueda de variables que necesita el proyecto
variables_objetivo = [
    'Engine RPM(rpm)',                  # Revoluciones por minuto del motor (PID 0C)
    'Engine Load(%)',                   # Carga calculada del motor (PID 04)
    'Engine Coolant Temperature(°F)',   # Temperatura del refrigerante (PID 05), en °F
    'Intake Air Temperature(°F)',       # Temperatura del aire de admisión (PID 0F), en °F
    'Intake Manifold Pressure(psi)',    # Presión del múltiple de admisión, sensor MAP (PID 0B)
    'Absolute Throttle Position B(%)',  # Posición absoluta B de la mariposa (PID 47)
    'Throttle Position(Manifold)(%)',   # Posición de la mariposa reportada por la ECU (PID 11)
    'Air Fuel Ratio(Measured)(:1)',     # Relación aire-combustible medida (sensor de oxígeno)
    'Speed (OBD)(mph)',                 # Velocidad del vehículo vía OBD (PID 0D), en mph
    'Fuel Level (From Engine ECU)(%)',  # Nivel de combustible según la ECU (PID 2F)
    'Run time since engine start(s)',   # Segundos desde el arranque del motor (PID 1F)
    'Voltage (Control Module)(V)',      # Voltaje del módulo de control (PID 42)
    'Voltage (OBD Adapter)(V)',         # Voltaje medido por el adaptador OBD-II (no es PID)
    'Acceleration Sensor(Total)(g)',    # Magnitud de la aceleración del teléfono, en g
    'G(x)',                             # Aceleración del teléfono, eje X (depende de su orientación; con gravedad)
    'G(y)',                             # Aceleración del teléfono, eje Y (ídem)
    'G(z)',                             # Aceleración del teléfono, eje Z (ídem)
    'GPS Speed (Meters/second)',        # Velocidad medida por GPS, en m/s
]

estado = {}
for clave, cols in esquemas.items():
    if clave.lower().endswith('.xlsx'):      # duplicado del CSV del 16-nov
        continue
    vac = set(auditoria.loc[auditoria['archivo'] == clave, 'columnas_vacias'].iloc[0])
    corto = (os.path.splitext(clave.split('/')[1])[0]
             .replace('trackLog-2022-', '').replace('torqueTrackLog', 'T'))
    estado[corto] = {v: ('vacía' if v in vac else 'ok') if v in cols else '-'
                     for v in variables_objetivo}

disponibilidad = pd.DataFrame(estado)
display(disponibilidad)
disponibilidad.to_csv(os.path.join(ruta_salida, 'disponibilidad_variables.csv'))

,nov-12_20-05-07,nov-13_00-03-52,nov-14_09-03-16,nov-14_13-01-38,nov-16_09-32-26,nov-16_09-44-58,nov.-10_09-23-59 (1),nov.-11_12-47-43,nov.-11_14-46-26,nov.-27_12-43-04,T(1),T(2),T(3),T(4),T(5),T
Engine RPM(rpm),ok,ok,ok,ok,ok,ok,ok,ok,ok,-,-,ok,-,-,-,-
Engine Load(%),ok,ok,ok,ok,ok,ok,ok,ok,ok,-,-,ok,-,-,-,-
Engine Coolant Temperature(°F),ok,ok,ok,ok,ok,ok,ok,ok,ok,-,-,-,-,-,-,-
Intake Air Temperature(°F),ok,ok,ok,ok,ok,ok,ok,ok,ok,-,-,-,-,-,-,-
Intake Manifold Pressure(psi),ok,ok,ok,ok,ok,ok,ok,ok,ok,-,-,-,-,-,-,-
Absolute Throttle Position B(%),ok,ok,ok,ok,ok,ok,ok,ok,ok,-,-,-,-,-,-,-
Throttle Position(Manifold)(%),ok,ok,ok,ok,ok,ok,ok,-,ok,-,-,ok,-,-,-,-
Air Fuel Ratio(Measured)(:1),ok,ok,ok,ok,ok,ok,ok,ok,ok,-,-,-,-,-,-,-
Speed (OBD)(mph),ok,ok,ok,ok,ok,ok,ok,ok,ok,-,-,-,-,-,-,-
Fuel Level (From Engine ECU)(%),ok,ok,ok,ok,ok,ok,ok,ok,ok,-,-,-,-,-,-,-
Run time since engine start(s),ok,ok,ok,ok,ok,ok,ok,ok,ok,-,-,-,-,-,-,-
Voltage (Control Module)(V),ok,ok,ok,ok,ok,ok,ok,ok,ok,-,-,-,-,-,-,-
Voltage (OBD Adapter)(V),ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,-,-,-,-,-,-
Acceleration Sensor(Total)(g),ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,-,-,-,-,-,-
G(x),ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok
G(y),ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok
G(z),ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok
GPS Speed (Meters/second),ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok

In [10]:
# Celda 10 -> Cobertura de variables por sesión única (usa variables_objetivo de la celda 9)
vistos = set()
filas_cobertura = []
for carpeta in (carpeta1, carpeta2):
    for ruta in sorted(Path(carpeta).iterdir()):
        if ruta.suffix.lower() != '.csv':
            continue
        filas, _ = leer_filas(ruta)
        for k, b in enumerate(partir_en_bloques(filas), start=1):
            huella = huella_bloque(b)
            if huella in vistos:                      # sesión ya contada en otro archivo
                continue
            vistos.add(huella)
            i_t = b['encabezado'].index('Device Time')
            tiempos = [normalizar_texto(r[i_t]) for r in b['filas'] if i_t < len(r)]
            fila = {'carpeta': ruta.parent.name, 'archivo': ruta.name, 'bloque': k,
                    'n_filas': len(b['filas']),
                    'primer_tiempo': tiempos[0] if tiempos else '',
                    'ultimo_tiempo': tiempos[-1] if tiempos else ''}
            for v in variables_objetivo:
                if v in b['encabezado'] and b['filas']:
                    i = b['encabezado'].index(v)
                    con_dato = sum(1 for r in b['filas']
                                   if i < len(r) and normalizar_texto(r[i]) not in FALTANTES)
                    fila[v] = round(100 * con_dato / len(b['filas']), 1)
                else:
                    fila[v] = None                    # la columna no existe en este bloque
            filas_cobertura.append(fila)

cobertura = pd.DataFrame(filas_cobertura)
cobertura[variables_objetivo] = cobertura[variables_objetivo].astype(float)
cobertura.insert(0, 'sesion', [f'S{n:02d}' for n in range(1, len(cobertura) + 1)])

print(f"Sesiones únicas: {len(cobertura)} | filas únicas: {cobertura['n_filas'].sum()}")
display(cobertura[['sesion', 'carpeta', 'archivo', 'bloque', 'n_filas', 'primer_tiempo', 'ultimo_tiempo']])
display(cobertura.set_index('sesion')[variables_objetivo].T)
cobertura.to_csv(os.path.join(ruta_salida, 'cobertura_sesiones.csv'), index=False)

Sesiones únicas: 18 | filas únicas: 30424

,sesion,carpeta,archivo,bloque,n_filas,primer_tiempo,ultimo_tiempo
0,S01,Measurement complementary,trackLog-2022-nov-12_20-05-07.csv,1,2955,12-nov-2022 20:05:18.394,12-nov-2022 20:31:35.894
1,S02,Measurement complementary,trackLog-2022-nov-13_00-03-52.csv,1,2260,13-nov-2022 00:08:01.613,13-nov-2022 00:26:51.113
2,S03,Measurement complementary,trackLog-2022-nov-14_09-03-16.csv,1,1625,14-nov-2022 09:31:39.429,14-nov-2022 09:45:11.421
3,S04,Measurement complementary,trackLog-2022-nov-14_13-01-38.csv,1,1928,14-nov-2022 13:02:22.085,14-nov-2022 13:18:25.584
4,S05,Measurement complementary,trackLog-2022-nov-16_09-32-26.csv,1,2957,16-nov-2022 09:33:04.532,16-nov-2022 10:00:16.532
5,S06,Measurement complementary,trackLog-2022-nov-16_09-44-58.csv,1,2013,16-nov-2022 10:01:54.434,16-nov-2022 10:18:40.435
6,S07,Measurement complementary,trackLog-2022-nov.-10_09-23-59 (1).csv,1,2787,10-nov.-2022 09:24:07.144,10-nov.-2022 09:47:20.141
7,S08,Measurement complementary,trackLog-2022-nov.-11_12-47-43.csv,1,3063,11-nov.-2022 12:47:50.319,11-nov.-2022 13:13:21.319
8,S09,Measurement complementary,trackLog-2022-nov.-11_14-46-26.csv,1,2858,11-nov.-2022 14:56:39.138,11-nov.-2022 15:20:27.637
9,S10,Measurement complementary,trackLog-2022-nov.-27_12-43-04.csv,1,876,27-nov.-2022 12:44:21.062,27-nov.-2022 12:58:56.060
10,S11,Mediciones Agosto 2024 Chiapas,torqueTrackLog(1).csv,1,850,21-ago-2024 08:16:07.301,21-ago-2024 08:30:16.212
11,S12,Mediciones Agosto 2024 Chiapas,torqueTrackLog(1).csv,2,1947,21-ago-2024 09:21:49.824,21-ago-2024 09:54:15.817
12,S13,Mediciones Agosto 2024 Chiapas,torqueTrackLog(1).csv,3,1108,21-ago-2024 12:44:25.201,21-ago-2024 13:02:52.193
13,S14,Mediciones Agosto 2024 Chiapas,torqueTrackLog(2).csv,1,4,22-ago-2024 07:01:14.348,22-ago-2024 07:01:17.329
14,S15,Mediciones Agosto 2024 Chiapas,torqueTrackLog(2).csv,2,1952,22-ago-2024 07:01:38.308,22-ago-2024 07:34:09.305
15,S16,Mediciones Agosto 2024 Chiapas,torqueTrackLog(2).csv,3,663,24-ago-2024 14:13:27.892,24-ago-2024 14:24:29.884
16,S17,Mediciones Agosto 2024 Chiapas,torqueTrackLog(2).csv,4,13,24-ago-2024 14:52:50.005,24-ago-2024 14:53:01.997
17,S18,Mediciones Agosto 2024 Chiapas,torqueTrackLog(4).csv,4,565,22-ago-2024 06:51:29.117,22-ago-2024 07:00:53.098

sesion,S01,S02,S03,S04,S05,S06,S07,S08,S09,S10,S11,S12,S13,S14,S15,S16,S17,S18
Engine RPM(rpm),100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,100.0,92.3,NaN
Engine Load(%),100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,100.0,92.3,NaN
Engine Coolant Temperature(°F),100.0,100.0,100.0,100.0,99.9,100.0,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Intake Air Temperature(°F),100.0,100.0,100.0,100.0,99.9,100.0,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Intake Manifold Pressure(psi),100.0,100.0,100.0,100.0,99.9,100.0,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Absolute Throttle Position B(%),100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Throttle Position(Manifold)(%),100.0,100.0,100.0,100.0,100.0,100.0,100.0,NaN,100.0,NaN,NaN,NaN,NaN,NaN,NaN,100.0,92.3,NaN
Air Fuel Ratio(Measured)(:1),100.0,100.0,100.0,100.0,99.7,100.0,100.0,99.4,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Speed (OBD)(mph),100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Fuel Level (From Engine ECU)(%),100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Run time since engine start(s),100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Voltage (Control Module)(V),100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Voltage (OBD Adapter)(V),100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Acceleration Sensor(Total)(g),100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
G(x),100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
G(y),100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
G(z),100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
GPS Speed (Meters/second),100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0

## 2. Inventario de Columnas y Preparación de Rutas de Datos

### Inventario de Columnas para `ruta1` (Measurement complementary)

In [ ]:
# Celda 5 RUTA 1
print(f"total de archivos: {len(listar_archivos(ruta1))}\n")
print(tabla_integridad(ruta1).to_string(index=False))

inventario1 = inventariar_columnas(ruta1)
comunes1, total1 = resumen_inventario(inventario1)

NameError: name 'listar_archivos' is not defined

### Inventario de Columnas para `ruta2` (Mediciones Agosto 2024 Chiapas)

In [ ]:

# Celda 6
print(f"Total de archivos: {len(listar_archivos(ruta2))}\n")
print(tabla_integridad(ruta2).to_string(index=False))

inventario2 = inventariar_columnas(ruta2)
comunes2, total2 = resumen_inventario(inventario2, detalle_no_comunes=True)

## 3. Selección y Carga de Variables Objetivo

CARGA DE LOS DATOS

In [ ]:
dataframes = []

for nombre_archivo in inventario1_filtrado.keys():
    ruta_completa = os.path.join(ruta1, nombre_archivo)
    df = pd.read_csv(ruta_completa) #Leer el archivo original
    df.columns = [col.strip() for col in df.columns]  # Se limpian los espacios
    df = df[variables_objetivo].copy()
    df['archivo_origen'] = nombre_archivo
    dataframes.append(df)

print(f"Total de dataframes cargados: {len(dataframes)}")

for nombre, df in zip(inventario1_filtrado.keys(), dataframes):
    print(f"{nombre}: {len(df)} filas, {len(df.columns)} columnas")

RECORDATORIO: ANTES DE REALIZAR EL ENTRENAMIENTO DE LA RED, SE ELIMINO LA COLUMNA DE "archivo_origen".

## 4. Limpieza y Normalización de Datos

### Limpieza de Valores Nulos y Formato Numérico

In [ ]:

import numpy as np

dataframes_limpios = []

for df in dataframes:
    df_limpio = df.copy()

    #Columnas de datos - No se considera la columna "archivo_origen"
    columnas_numericas = [col for col in variables_objetivo]

    for col in columnas_numericas:

        #Limpieza de espacios en los valores de las celdas
        serie_texto = df_limpio[col].astype(str).str.strip()

        '''
        Algunos datos usan '-' para datos negativos, de este modo
        solo se llega a remplazar los '-' que estan 'solos', por NaN.
        '''
        serie_texto = serie_texto.replace(r'^-$', np.nan, regex=True)

        df_limpio[col] = pd.to_numeric(serie_texto, errors='coerce')

    dataframes_limpios.append(df_limpio)
print(f"Dataframes limpios: {len(dataframes_limpios)}\n")

#Resumen de vacíos reales por columna, por archivo
for nombre, df in zip(inventario1_filtrado.keys(), dataframes_limpios):
    nulos = df[variables_objetivo].isna().sum()
    nulos_totales = nulos.sum()
    print(f"{nombre}: {nulos_totales} valores nulos totales de {len(df) * len(variables_objetivo)} celdas")
#